### ISSUE TITLE
在windows下面部署docker后运行py-plugin报错

### ISSUE THREAD

**Issue by Somnusochi** [SirlyDreamer/Yunzai-Bot#11]
<img width="759" alt="image" src="https://user-images.githubusercontent.com/14160184/187614470-b9f8b505-66f9-4d79-87fa-034f4d1e3dcf.png">

<img width="999" alt="image" src="https://user-images.githubusercontent.com/14160184/187613850-79833fea-2e58-4349-ab0c-9c12906439a4.png">

```
UnicodeEncodeError: ‘ascii’ codec can’t encode characters in posit
```
百度了一下好像是docker镜像容器的语言环境问题，暂时不知道怎么解决，希望大佬能帮忙看看

**Comment by Somnusochi** [comment]
是使用py-plugin里面的米游币自动兑换插件，在要求输入cookie以后返回的报错信息

**Comment by SirlyDreamer** [comment]
这个好像是米游币自动兑换插件的问题，参见原插件issue：
[https://gitee.com/py-plugin-apps/myb_exchange/issues/I5ORMM](https://gitee.com/py-plugin-apps/myb_exchange/issues/I5ORMM)

**Comment by Somnusochi** [comment]
好吧，最近还有一个问题，重启的时候载入插件发生报错，我之前以为是插件那边的问题

前几天是发生在`mao-plugin`上的，我把`mao-plugin`文件夹内的git文件夹删除了，使用旧版本不更新就能正常载入

然后今天重启的时候`xiaoyao-cvs-plugin`也报了同样的错，如果同样也把git文件夹删除，用回旧的版本就没问题

<img width="521" alt="image" src="https://user-images.githubusercontent.com/14160184/188255851-59bf14b5-3aef-4cfb-aee1-e1c47ce25cb7.png">

**Comment by Somnusochi** [comment]
好吧，暂时还是不知道怎么解决
