### ISSUE TITLE
docker 部署 yunzai 使用npm start报错

### ISSUE THREAD

**Issue by mqh9007** [SirlyDreamer/Yunzai-Bot#12]
报错内容
Error: EACCES: permission denied, mkdir '/root/.pm2/logs'
Error: EACCES: permission denied, open '/root/.pm2/module_conf.json' 

docker镜像是centos7.9.2009

**Comment by SirlyDreamer** [comment]
本项目是基于 Alpine 3.16 和 Debian 10 构建的镜像

并不知道CentOS 7是从哪来的QwQ

如果需要自己构建镜像，请参考本项目的Dockerfile，不然我也不知道哪里出了问题QuQ
