### ISSUE TITLE
重启后丢失绑定uid等数据，如何开启AOF持久化数据

### ISSUE THREAD

**Issue by Flyky** [SirlyDreamer/Yunzai-Bot#16]
[https://github.com/Le-niao/Yunzai-Bot/issues/557](https://github.com/Le-niao/Yunzai-Bot/issues/557)
目前yunzai-redis的容器似乎没有配置映射redis.conf等配置文件

**Comment by SirlyDreamer** [comment]
已添加docker-compose.yaml中Redis配置文件的部分，请自行下载并修改composefile
