### ISSUE TITLE
关于ck绑定与#用户统计 命令的相关问题

### ISSUE THREAD

**Issue by fsqhn** [SirlyDreamer/Yunzai-Bot#18]
昨晚用docker辅助脚本部署了一个，然后今天测试中发现很快就提示ck查询次数用完了，翻issues时发现了  https://github.com/Le-niao/Yunzai-Bot/issues/557  ，然后按人家的说法对 /etc/redis.conf 文件进行了修改。但是由于本人纯纯小白，不清楚下一步该如何进行。希望有更详细的教程。
另外，在使用过程中发喵喵插件的#用户统计 功能机器人这边完全没反应，但使用以前v2版本的#用户统计指令中提示的 #使用全部ck  又能正常开启使用全部ck。此外，希望能增加v2版本的检查ck功能。遇到这种问题的时候能更快速的检查原因。

顺带一提，使用#xx圣遗物  的指令时会先跳出“公共ck查询次数已用完，暂无法查询新uid”的提示，然后再发喵喵插件的圣遗物分析图片，是不是跟哪个功能指令重复了？？

**Comment by SirlyDreamer** [comment]
昨天刚刚更新了关于Redis配置文件的设置项，操作步骤如下：
1.将修改好的redis.conf放入./redis/config文件夹内
2.取消注释docker-compose.yml文件的这两行：
https://github.com/SirlyDreamer/Yunzai-Bot/blob/main/docker-compose.yaml#L33
https://github.com/SirlyDreamer/Yunzai-Bot/blob/main/docker-compose.yaml#L36
然后重新docker compose up -d就可以了

**Comment by SirlyDreamer** [comment]
关于指令重复的问题，建议去云崽仓库反应，本repo只负责关于docker部署的部分（其他的不会）

**Comment by fsqhn** [comment]
感谢指导，然后遇到了新的问题。 首先是redis文件夹内没有config文件夹……我是在“/root/1”文件夹下执行的脚本，然后只在“/root/1/yunzai-bot”文件夹下有redis文件夹跟docker-compose.yml文件。
另外，我编辑docker-compose.yml文件时内部如下：【
version: "3.9"
services:
  yunzai-bot:
    container_name: yunzai-bot
    image: swr.cn-south-1.myhuaweicloud.com/sirly/yunzai-bot:v3plus
    restart: always
    volumes:
      - ./yunzai/config:/app/Yunzai-Bot/config/config/ # 配置文件
      - ./yunzai/genshin_config:/app/Yunzai-Bot/plugins/genshin/config # 配置文件
      - ./yunzai/logs:/app/Yunzai-Bot/logs # 日志文件
      - ./yunzai/data:/app/Yunzai-Bot/data # 数据文件
      - ./yunzai/plugins/example:/app/Yunzai-Bot/plugins/example # js 插件
      # 以下目录是插件目录，安装完插件后需要手动添加映射
      - ./yunzai/plugins/miao-plugin:/app/Yunzai-Bot/plugins/miao-plugin                  # 喵喵插件
      - ./yunzai/plugins/py-plugin:/app/Yunzai-Bot/plugins/py-plugin                      # 新py插件
      - ./yunzai/plugins/xiaoyao-cvs-plugin:/app/Yunzai-Bot/plugins/xiaoyao-cvs-plugin    # 图鉴插件
    depends_on:
      redis: { condition: service_healthy }

  redis:
    container_name: yunzai-redis
    image: redis:alpine
    restart: always
    volumes:
      - ./redis/data:/data
      - ./redis/logs:/logs
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      start_period: 10s
      interval: 5s
      timeout: 1s
】
并没有找到您说的需要取消注释的那两行。
是否是因为我找错文件跟文件夹了？

**Comment by SirlyDreamer** [comment]
1.没有文件夹创建一个即可
2.从[https://github.com/SirlyDreamer/Yunzai-Bot/blob/main/docker-compose.yaml](https://github.com/SirlyDreamer/Yunzai-Bot/blob/main/docker-compose.yaml#L33)复制最新版的docker-compose.yml然后修改就行了

**Comment by fsqhn** [comment]
按照最新版的docker-compose.yml，并修改为如下后：【 
redis:
    container_name: yunzai-redis
    image: redis:alpine
    restart: always
    volumes:
      # 前往 https://download.redis.io/redis-stable/redis.conf 下载配置文件，放入 ./redis/config 文件夹中
      - ./redis/config:/etc/redis/    # Redis配置文件
      - ./redis/data:/data
      - ./redis/logs:/logs
    command: /etc/redis/redis.conf    # 取消注释以应用Redis配置文件
    healthcheck:
      test: [ "CMD", "redis-cli", "PING" ]
      start_period: 10s
      interval: 5s
      timeout: 1s
】，运行docker compose up  提示：“
[+] Running 2/1
 ⠿ Container yunzai-redis  Recreated                                                                           0.1s
 ⠿ Container yunzai-bot    Recreated                                                                           0.1s
Attaching to yunzai-bot, yunzai-redis
yunzai-redis  | 
yunzai-redis  | *** FATAL CONFIG FILE ERROR (Redis 7.0.4) ***
yunzai-redis  | Reading the configuration file, at line 247
yunzai-redis  | >>> 'dir /var/lib/redis'
yunzai-redis  | No such file or directory
yunzai-redis exited with code 1
container for service "redis" is unhealthy
”，再不断修改中发现需要注释掉 command: /etc/redis/redis.conf 这行才能成功启动，但按这文件的说法应该等于没应用配置文件？

**Comment by SirlyDreamer** [comment]
配置文件有问题，貌似是第247行设置的目录无效，请自行修改或注释掉

**Comment by fsqhn** [comment]
好的，谢谢。把那行注释掉后可以成功启动了，cookie也依然还在。十分感谢！

**Comment by xingyunlee12138** [comment]
大佬请问下，我把配置文件已经放在/test/yunzai-bot/redis/config这里面，配置文件也改了

version: "3.9"
services:
  yunzai-bot:
    container_name: yunzai-bot
    # build: ./docker # 使用 Dockerfile 本地构建
    image: sirly/yunzai-bot:v3plus
    # image: swr.cn-south-1.myhuaweicloud.com/sirly/yunzai-bot:v3plus   # 使用扩展镜像，包含ffmpeg和python
    # image: sirly/yunzai-bot:v3                                        # Docker Hub源
    # image: sirly/yunzai-bot:v3plus 
    restart: always
    # ports:
    #   - "50831:50831"                                                 # 映射锅巴插件端口，格式"主机端口:容器内部端口"
    volumes:
      - ./yunzai/config/:/app/Yunzai-Bot/config/config/                 # Bot基础配置文件
      - ./yunzai/genshin_config:/app/Yunzai-Bot/plugins/genshin/config  # 公共Cookie，云崽功能配置文件
      - ./yunzai/logs:/app/Yunzai-Bot/logs                              # 日志文件
      - ./yunzai/data:/app/Yunzai-Bot/data                              # 数据文件
      - ./yunzai/plugins/example:/app/Yunzai-Bot/plugins/example # js 插件
      # 以下目录是插件目录，安装完插件后需要手动添加映射
      - ./yunzai/plugins/miao-plugin:/app/Yunzai-Bot/plugins/miao-plugin                  # 喵喵插件
      - ./yunzai/plugins/py-plugin:/app/Yunzai-Bot/plugins/py-plugin                      # 新py插件
      - ./yunzai/plugins/xiaoyao-cvs-plugin:/app/Yunzai-Bot/plugins/xiaoyao-cvs-plugin    # 图鉴插件
      - ./yunzai/plugins/zhi-plugin:/app/Yunzai-Bot/plugins/zhi-plugin                    # 白纸插件
    depends_on:
      redis: { condition: service_healthy }

  redis:
    container_name: yunzai-redis
    image: redis:alpine
    restart: always
    volumes:
      # 前往 https://download.redis.io/redis-stable/redis.conf 下载配置文件，放入 ./redis/config 文件夹中
      - ./redis/config:/etc/redis/    # Redis配置文件
      - ./redis/data:/data
      - ./redis/logs:/logs
    command: /etc/redis/redis.conf    # 取消注释以应用Redis配置文件
    healthcheck:
      test: [ "CMD", "redis-cli", "PING" ]
      start_period: 10s
      interval: 5s
      timeout: 1s
      
   但是启动的时候提示
[YzBot][22:10:30.691][MARK] Yunzai-Bot 启动中...
[YzBot][22:10:30.694][MARK] 连接redis....
[YzBot][22:10:30.746][ERRO] redis链接失败！
是哪里弄错了吗

**Comment by SirlyDreamer** [comment]
> 大佬请问下，我把配置文件已经放在/test/yunzai-bot/redis/config这里面，配置文件也改了
> 
> version: "3.9" services: yunzai-bot: container_name: yunzai-bot # build: ./docker # 使用 Dockerfile 本地构建 image: sirly/yunzai-bot:v3plus # image: swr.cn-south-1.myhuaweicloud.com/sirly/yunzai-bot:v3plus # 使用扩展镜像，包含ffmpeg和python # image: sirly/yunzai-bot:v3 # Docker Hub源 # image: sirly/yunzai-bot:v3plus restart: always # ports: # - "50831:50831" # 映射锅巴插件端口，格式"主机端口:容器内部端口" volumes: - ./yunzai/config/:/app/Yunzai-Bot/config/config/ # Bot基础配置文件 - ./yunzai/genshin_config:/app/Yunzai-Bot/plugins/genshin/config # 公共Cookie，云崽功能配置文件 - ./yunzai/logs:/app/Yunzai-Bot/logs # 日志文件 - ./yunzai/data:/app/Yunzai-Bot/data # 数据文件 - ./yunzai/plugins/example:/app/Yunzai-Bot/plugins/example # js 插件 # 以下目录是插件目录，安装完插件后需要手动添加映射 - ./yunzai/plugins/miao-plugin:/app/Yunzai-Bot/plugins/miao-plugin # 喵喵插件 - ./yunzai/plugins/py-plugin:/app/Yunzai-Bot/plugins/py-plugin # 新py插件 - ./yunzai/plugins/xiaoyao-cvs-plugin:/app/Yunzai-Bot/plugins/xiaoyao-cvs-plugin # 图鉴插件 - ./yunzai/plugins/zhi-plugin:/app/Yunzai-Bot/plugins/zhi-plugin # 白纸插件 depends_on: redis: { condition: service_healthy }
> 
> redis: container_name: yunzai-redis image: redis:alpine restart: always volumes: # 前往 https://download.redis.io/redis-stable/redis.conf 下载配置文件，放入 ./redis/config 文件夹中 - ./redis/config:/etc/redis/ # Redis配置文件 - ./redis/data:/data - ./redis/logs:/logs command: /etc/redis/redis.conf # 取消注释以应用Redis配置文件 healthcheck: test: [ "CMD", "redis-cli", "PING" ] start_period: 10s interval: 5s timeout: 1s
> 
> 但是启动的时候提示 [YzBot][22:10:30.691][MARK] Yunzai-Bot 启动中... [YzBot][22:10:30.694][MARK] 连接redis.... [YzBot][22:10:30.746][ERRO] redis链接失败！ 是哪里弄错了吗

/yunzai/config/redis.yaml里redis的地址改成redis，不是127.0.0.1

**Comment by xingyunlee12138** [comment]
里面是这样的，没有动过他
# redis地址
host: redis
# redis端口
port: 6379 
# redis密码，没有密码可以为空    
password: 
# redis数据库    
db: 0
主要是我把这上下两个注释掉他又能运行，但是cookie又没了，等于没改
- ./redis/config:/etc/redis/ # Redis配置文件
- ./redis/data:/data
- ./redis/logs:/logs
command: /etc/redis/redis.conf # 取消注释以应用Redis配置文件

**Comment by xingyunlee12138** [comment]
> > 大佬请问下，我把配置文件已经放在/test/yunzai-bot/redis/config这里面，配置文件也改了
> > 版本： “3.9” 服务： 云宰机器人： container_name： 云宰机器人 # build： ./docker # 使用 Dockerfile 本地构建映像： sirly/yunzai-bot：v3plus # image： swr.cn-south-1.myhuaweicloud.com/sirly/yunzai-bot:v3plus # 使用扩展镜像，包含ffmpeg和python # 图像： sirly/yunzai-bot：v3 # Docker Hub源 # image： sirly/yunzai-bot：v3plus restart： 总是 # 端口： # - “50831：50831” # 映射锅巴插件端口，格式“主机端口：容器内部端口” 卷： -./yunzai/config/：/app/Yunzai-Bot/config/config/ # Bot基础配置文件 - ./yunzai/genshin_config：/app/云泽-Bot/plugins/genshin/config # 公共Cookie，云崽功能配置文件 - ./云寨/logs：/app/云宰-Bot/logs # 日志文件 - ./yunzai/data #数据文件 - ./yunzai/plugins/example：/app/Yunzai-Bot/plugins/example # js 插件 # 以下目录是插件目录，安装完插件后需要手动添加映射 - ./yunzai/plugins/plugins/miao-plugin：/app/Yunzai-Bot/plugins/插件/苗-插件 # 喵喵插件 - ./yunzai/py-plugins：/app/yunzai/py-plugins#图鉴插件 - ./云彩/插件/芝-插件：/app/云宰机器人/插件/芝-插件 # 白纸插件 depends_on： redis： { 条件： service_healthy }
> > redis： container_name： yunzai-redis 图像： redis：alpine restart： 总是卷： # 前往 https://download.redis.io/redis-stable/redis.conf 下载配置文件，放入 ./redis/config 文件夹中 - ./redis/config：/etc/redis/ # Redis配置文件 - ./redis/data：/data - ./redis/logs：/logs 命令： /etc/redis/redis.conf # 取消注释以应用Redis配置文件健康检查： 测试： [ “CMD”， “redis-cli”， “PING” ] start_period： 10s 间隔： 5s 超时： 1s
> > 但是启动的时候提示 [YzBot][22：10：30.691][MARK] Yunzai-Bot 启动中...[易兹博特][22:10:30.694][MARK] 连接redis....[易兹博特][22:10:30.746][ERRO] redis链接失败！ 是哪里弄错了吗
> 
> /yunzai/config/redis.yaml里redis的地址改成redis，不是127.0.0.1

问个很小白的问题，# 前往 https://download.redis.io/redis-stable/redis.conf 下载配置文件的配置文件，打开里面本来就是每一行都是#开头的吗。像这样的
# Redis configuration file example.
#
# Note that in order to read the configuration file, Redis must be
# started with the file path as first argument:
#
# ./redis-server /path/to/redis.conf

# Note on units: when memory size is needed, it is possible to specify
# it in the usual form of 1k 5GB 4M and so forth:
#
# 1k => 1000 bytes
# 1kb => 1024 bytes
# 1m => 1000000 bytes
# 1mb => 1024*1024 bytes
# 1g => 1000000000 bytes
# 1gb => 1024*1024*1024 bytes
#
# units are case insensitive so 1GB 1Gb 1gB are all the same.

################################## INCLUDES ###################################

# Include one or more other config files here.  This is useful if you
# have a standard template that goes to all Redis servers but also need
# to customize a few per-server settings.  Include files can include
# other files, so use this wisely.

**Comment by xingyunlee12138** [comment]
> > 大佬请问下，我把配置文件已经放在/test/yunzai-bot/redis/config这里面，配置文件也改了
> > 版本： “3.9” 服务： 云宰机器人： container_name： 云宰机器人 # build： ./docker # 使用 Dockerfile 本地构建映像： sirly/yunzai-bot：v3plus # image： swr.cn-south-1.myhuaweicloud.com/sirly/yunzai-bot:v3plus # 使用扩展镜像，包含ffmpeg和python # 图像： sirly/yunzai-bot：v3 # Docker Hub源 # image： sirly/yunzai-bot：v3plus restart： 总是 # 端口： # - “50831：50831” # 映射锅巴插件端口，格式“主机端口：容器内部端口” 卷： -./yunzai/config/：/app/Yunzai-Bot/config/config/ # Bot基础配置文件 - ./yunzai/genshin_config：/app/云泽-Bot/plugins/genshin/config # 公共Cookie，云崽功能配置文件 - ./云寨/logs：/app/云宰-Bot/logs # 日志文件 - ./yunzai/data #数据文件 - ./yunzai/plugins/example：/app/Yunzai-Bot/plugins/example # js 插件 # 以下目录是插件目录，安装完插件后需要手动添加映射 - ./yunzai/plugins/plugins/miao-plugin：/app/Yunzai-Bot/plugins/插件/苗-插件 # 喵喵插件 - ./yunzai/py-plugins：/app/yunzai/py-plugins#图鉴插件 - ./云彩/插件/芝-插件：/app/云宰机器人/插件/芝-插件 # 白纸插件 depends_on： redis： { 条件： service_healthy }
> > redis： container_name： yunzai-redis 图像： redis：alpine restart： 总是卷： # 前往 https://download.redis.io/redis-stable/redis.conf 下载配置文件，放入 ./redis/config 文件夹中 - ./redis/config：/etc/redis/ # Redis配置文件 - ./redis/data：/data - ./redis/logs：/logs 命令： /etc/redis/redis.conf # 取消注释以应用Redis配置文件健康检查： 测试： [ “CMD”， “redis-cli”， “PING” ] start_period： 10s 间隔： 5s 超时： 1s
> > 但是启动的时候提示 [YzBot][22：10：30.691][MARK] Yunzai-Bot 启动中...[易兹博特][22:10:30.694][MARK] 连接redis....[易兹博特][22:10:30.746][ERRO] redis链接失败！ 是哪里弄错了吗
> 
> /yunzai/config/redis.yaml里redis的地址改成redis，不是127.0.0.1

问个很小白的问题，这个下载的 # 前往 https://download.redis.io/redis-stable/redis.conf 下载配置文件。这里面的配置文件，本来就是#开头的吗。
# Redis configuration file example.
#
# Note that in order to read the configuration file, Redis must be
# started with the file path as first argument:
#
# ./redis-server /path/to/redis.conf

# Note on units: when memory size is needed, it is possible to specify
# it in the usual form of 1k 5GB 4M and so forth:
#
# 1k => 1000 bytes
# 1kb => 1024 bytes
# 1m => 1000000 bytes
# 1mb => 1024*1024 bytes
# 1g => 1000000000 bytes
# 1gb => 1024*1024*1024 bytes
#
# units are case insensitive so 1GB 1Gb 1gB are all the same.

################################## INCLUDES ###################################

# Include one or more other config files here.  This is useful if you
# have a standard template that goes to all Redis servers but also need
# to customize a few per-server settings.  Include files can include
# other files, so use this wisely.

**Comment by xingyunlee12138** [comment]
> > 大佬请问下，我把配置文件已经放在/test/yunzai-bot/redis/config这里面，配置文件也改了
> > 版本： “3.9” 服务： 云宰机器人： container_name： 云宰机器人 # build： ./docker # 使用 Dockerfile 本地构建映像： sirly/yunzai-bot：v3plus # image： swr.cn-south-1.myhuaweicloud.com/sirly/yunzai-bot:v3plus # 使用扩展镜像，包含ffmpeg和python # 图像： sirly/yunzai-bot：v3 # Docker Hub源 # image： sirly/yunzai-bot：v3plus restart： 总是 # 端口： # - “50831：50831” # 映射锅巴插件端口，格式“主机端口：容器内部端口” 卷： -./yunzai/config/：/app/Yunzai-Bot/config/config/ # Bot基础配置文件 - ./yunzai/genshin_config：/app/云泽-Bot/plugins/genshin/config # 公共Cookie，云崽功能配置文件 - ./云寨/logs：/app/云宰-Bot/logs # 日志文件 - ./yunzai/data #数据文件 - ./yunzai/plugins/example：/app/Yunzai-Bot/plugins/example # js 插件 # 以下目录是插件目录，安装完插件后需要手动添加映射 - ./yunzai/plugins/plugins/miao-plugin：/app/Yunzai-Bot/plugins/插件/苗-插件 # 喵喵插件 - ./yunzai/py-plugins：/app/yunzai/py-plugins#图鉴插件 - ./云彩/插件/芝-插件：/app/云宰机器人/插件/芝-插件 # 白纸插件 depends_on： redis： { 条件： service_healthy }
> > redis： container_name： yunzai-redis 图像： redis：alpine restart： 总是卷： # 前往 https://download.redis.io/redis-stable/redis.conf 下载配置文件，放入 ./redis/config 文件夹中 - ./redis/config：/etc/redis/ # Redis配置文件 - ./redis/data：/data - ./redis/logs：/logs 命令： /etc/redis/redis.conf # 取消注释以应用Redis配置文件健康检查： 测试： [ “CMD”， “redis-cli”， “PING” ] start_period： 10s 间隔： 5s 超时： 1s
> > 但是启动的时候提示 [YzBot][22：10：30.691][MARK] Yunzai-Bot 启动中...[易兹博特][22:10:30.694][MARK] 连接redis....[易兹博特][22:10:30.746][ERRO] redis链接失败！ 是哪里弄错了吗
> 
> /yunzai/config/redis.yaml里redis的地址改成redis，不是127.0.0.1

问个很小白的问题# 前往 https://download.redis.io/redis-stable/redis.conf 下载配置文件，打开后里面的每一行本来就是有#开头的吗

**Comment by SirlyDreamer** [comment]
> > > 大佬请问下，我把配置文件已经放在/test/yunzai-bot/redis/config这里面，配置文件也改了
> > > 版本： “3.9” 服务： 云宰机器人： container_name： 云宰机器人 # build： ./docker # 使用 Dockerfile 本地构建映像： sirly/yunzai-bot：v3plus # image： swr.cn-south-1.myhuaweicloud.com/sirly/yunzai-bot:v3plus # 使用扩展镜像，包含ffmpeg和python # 图像： sirly/yunzai-bot：v3 # Docker Hub源 # image： sirly/yunzai-bot：v3plus restart： 总是 # 端口： # - “50831：50831” # 映射锅巴插件端口，格式“主机端口：容器内部端口” 卷： -./yunzai/config/：/app/Yunzai-Bot/config/config/ # Bot基础配置文件 - ./yunzai/genshin_config：/app/云泽-Bot/plugins/genshin/config # 公共Cookie，云崽功能配置文件 - ./云寨/logs：/app/云宰-Bot/logs # 日志文件 - ./yunzai/data #数据文件 - ./yunzai/plugins/example：/app/Yunzai-Bot/plugins/example # js 插件 # 以下目录是插件目录，安装完插件后需要手动添加映射 - ./yunzai/plugins/plugins/miao-plugin：/app/Yunzai-Bot/plugins/插件/苗-插件 # 喵喵插件 - ./yunzai/py-plugins：/app/yunzai/py-plugins#图鉴插件 - ./云彩/插件/芝-插件：/app/云宰机器人/插件/芝-插件 # 白纸插件 depends_on： redis： { 条件： service_healthy }
> > > redis： container_name： yunzai-redis 图像： redis：alpine restart： 总是卷： # 前往 https://download.redis.io/redis-stable/redis.conf 下载配置文件，放入 ./redis/config 文件夹中 - ./redis/config：/etc/redis/ # Redis配置文件 - ./redis/data：/data - ./redis/logs：/logs 命令： /etc/redis/redis.conf # 取消注释以应用Redis配置文件健康检查： 测试： [ “CMD”， “redis-cli”， “PING” ] start_period： 10s 间隔： 5s 超时： 1s
> > > 但是启动的时候提示 [YzBot][22：10：30.691][MARK] Yunzai-Bot 启动中...[易兹博特][22:10:30.694][MARK] 连接redis....[易兹博特][22:10:30.746][ERRO] redis链接失败！ 是哪里弄错了吗
> > 
> > 
> > /yunzai/config/redis.yaml里redis的地址改成redis，不是127.0.0.1
> 
> 问个很小白的问题# 前往 https://download.redis.io/redis-stable/redis.conf 下载配置文件，打开后里面的每一行本来就是有#开头的吗

是的，大部分都是注释

**Comment by SirlyDreamer** [comment]
关于Docker配置Redis容器持久化的问题请看这里
https://github.com/SirlyDreamer/Yunzai-Bot/issues/23
