### ISSUE TITLE
登陆的时候提示找不到日期格式

### ISSUE THREAD

**Issue by Kkong233** [SirlyDreamer/Yunzai-Bot#19]
登陆最后它报错然后提示找不到包 Cannot find package 'date-format' imported from D:\yunzai\Yunzai-Bot\lib\app\dailyNote.js    有什么解决办法吗佬qwq

**Comment by SirlyDreamer** [comment]
`npm install date-format`

这不是docker部署的问题吧qwq，看起来你使用windows部署的yunzaiv2

**Comment by Kkong233** [comment]
> `npm install date-format`
> 
> 这不是docker部署的问题吧qwq，看起来你使用Windows部署的yunzaiv2

是的，麻烦佬了qwq  非常感谢！！
