### ISSUE TITLE
v2安装yunzai启动失败

### ISSUE THREAD

**Issue by 1294266616** [SirlyDreamer/Yunzai-Bot#21]
日志文件
[_yunzai-bot_logs.txt](https://github.com/SirlyDreamer/Yunzai-Bot/files/9609612/_yunzai-bot_logs.txt)
部分截图
![image](https://user-images.githubusercontent.com/52421598/191314315-efaceaaa-d0ad-40a2-8b3d-69901d05e043.png)

**Comment by SirlyDreamer** [comment]
这是因为云崽更新的时候冲突了。

请尝试使用`docker compose pull`更新镜像（如果手动修改过js请先使用`docker cp`命令备份)
