### ISSUE TITLE
配置Redis文件持久化后docker-compose无法启动

### ISSUE THREAD

**Issue by keaiye** [SirlyDreamer/Yunzai-Bot#22]
![image](https://user-images.githubusercontent.com/43440669/192093084-5c4b5ec5-4c07-47c0-847c-acafceae9345.png)

**Comment by SirlyDreamer** [comment]
请检查一下redis.conf文件是否有误，前往 https://download.redis.io/redis-stable/redis.conf 下载配置文件

可以通过docker-compose up前台启动查看日志

**Comment by SirlyDreamer** [comment]
`docker logs yunzai-redis` 看看日志

**Comment by SirlyDreamer** [comment]
先`docker compose down`再`docker compose up`看看

**Comment by SirlyDreamer** [comment]
这样我也看不出什么信息来啊qwq
