### ISSUE TITLE
登陆QQ账号需要滑动验证，但无法输入滑动验证助手返回的相关信息

### ISSUE THREAD

**Issue by fsqhn** [SirlyDreamer/Yunzai-Bot#27]
yunzai-bot    | 
yunzai-bot    | [YzBot][13:23:30.350][MARK] Yunzai-Bot 启动中...
yunzai-bot    | [YzBot][13:23:30.352][MARK] 连接redis....
yunzai-bot    | [YzBot][13:23:30.370][MARK] 连接redis成功
yunzai-bot    | [YzBot][13:23:30.385][MARK] ----------
yunzai-bot    | [YzBot][13:23:30.385][MARK] Package Version: oicq@2.3.1 (Released on 2022/6/21)
yunzai-bot    | [YzBot][13:23:30.386][MARK] View Changelogs：https://github.com/takayama-lily/oicq/releases
yunzai-bot    | [YzBot][13:23:30.386][MARK] ----------
yunzai-bot    | [YzBot][13:23:30.509][MARK] 120.232.31.106:8080 connected
yunzai-bot    | [YzBot][13:23:30.650][MARK] 收到滑动验证码，请访问以下地址完成滑动，并从网络响应中取出ticket输入：https://ssl.captcha.qq.com/template/wireless_mqq_captcha.html?style=simple&aid=16&uin=2377510578&sid=6884834522773132498&cap_cd=Ns6ElvilG7pfHAc1vMezVR8-a4WvWddBhb3J_fjgBU8aJpCK5iKO1A**&clientype=1&apptype=2
yunzai-bot    | 
yunzai-bot    | 
yunzai-bot    | ------------------↓↓滑动验证链接↓↓----------------------
yunzai-bot    | 
yunzai-bot    | https://ssl.captcha.qq.com/template/wireless_mqq_captcha.html?style=simple&aid=16&uin=2377510578&sid=6884834522773132498&cap_cd=Ns6ElvilG7pfHAc1vMezVR8-a4WvWddBhb3J_fjgBU8aJpCK5iKO1A**&clientype=1&apptype=2
yunzai-bot    | 
yunzai-bot    | --------------------------------------------------------
yunzai-bot    | 提示：打开上面链接获取ticket，可使用【滑动验证app】获取
yunzai-bot    | 链接存在有效期，请尽快操作，多次操作失败可能会被冻结
yunzai-bot    | 滑动验证app下载地址：https://wwp.lanzouy.com/i6w3J08um92h 密码:3kuu
yunzai-bot    | 
yunzai-bot    | ? 触发滑动验证，需要获取ticket通过验证，请选择获取方式: (Use arrow keys)
yunzai-bot    | ? 1.手动获取ticket 

然后就卡主了，理论上应该需要选择手动获取ticket 或者印象中应该可以调整为采用请求码的，但是完全没办法输入任何东西，按回车也只是刷新屏幕而已。
该如何处理？

**Comment by SirlyDreamer** [comment]
`docker compose up`只是启动容器并打印日志，不提供可交互shell

需要输入信息，请先`docker compose up -d`后台启动镜像，然后`docker exec -it yunzai-bot /bin/bash`(精简镜像是/bin/sh)进入容器的shell，输入node app启动云崽

**Comment by fsqhn** [comment]
感谢，已经解决了
