### ISSUE TITLE
docker源上的版本是不是有段时间没更新了

### ISSUE THREAD

**Issue by fsqhn** [SirlyDreamer/Yunzai-Bot#28]
最近每次重启都要重新下依赖，猫猫插件也是维持在10月23日的版本，而且还每次手动更新都提示
Error: Command failed: git -C ./plugins/miao-plugin/ pull --no-rebase
From https://gitee.com/yoimiya-kokomi/miao-plugin
   e24726b..c79ac0d  master     -> origin/master
error: Unable to create '/app/Yunzai-Bot/plugins/miao-plugin/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
Updating 92419e1..c79ac0d

**Comment by SirlyDreamer** [comment]
镜像已更新

喵喵插件的问题是git未完全退出导致的。删除喵喵插件目录的`./.git/index.lock`即可解决

**Comment by fsqhn** [comment]
好的，已经能手动更新了。谢谢大佬。
