### ISSUE TITLE
启动报错 [温馨提示]当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面

### ISSUE THREAD

**Issue by shuangxunian** [SirlyDreamer/Yunzai-Bot#29]
在原来的issue里面搜没有搜到适合docker解决的方法 这个大佬们有什么合适的方法去解决吗

**Comment by SirlyDreamer** [comment]
参照issue https://github.com/Le-niao/Yunzai-Bot/issues/846

Docker部署云崽的data文件夹在`./yunzai/data/`，其他操作均相同

**Comment by shuangxunian** [comment]
get thanks~
